#!/bin/bash

# build project via docker run, eg
# usage: docker-run-ci <build-dir> [ VAR=VALUE ... ] [ target ... ]
# example: ./ci/docker-run-ci ./build-dir MPQC_BUILD_DEPENDENCIES_FROM_SOURCE=OFF ENABLE_CUDA=ON all check

project=$(basename $PWD)
image=valeevgroup/ubuntu
name=$USER.${project}.build
project_source_dir=$PWD

script="
cd /builds/ValeevGroup/${project}

git checkout .
git log -1

./ci/valeevgroup-ci ./build $@;

bash
"

echo -n "Removing previous build container: "
docker rm -f ${name}

echo "
Running new build of ${project_source_dir} on ${name}
* Use CTRL-p CTRL-q to dettach
* To reattach use: docker start -a -i ${name}
"
#sleep 1

docker run --name ${name} -ti \
       -v ${project_source_dir}/.git:/builds/ValeevGroup/${project}/.git \
       ${image} bash -c "$script"
