#!/bin/bash

# build project via docker run, eg
# usage: docker-run-ci [ VAR=VALUE ... ] [ target ... ]
# example: ./ci/docker-run-ci TA_PYTHON=OFF ENABLE_CUDA=ON all check

project=$(basename $PWD)
image=valeevgroup/ubuntu:${VALEEVGROUP_UBUNTU_TAG:-latest}
name=$USER.${project}.build
project_source_dir=$PWD

script="cd /builds/ValeevGroup/${project}

echo '# git checkout .'
git checkout .
echo

echo '# git log -1'
git log -1
echo

./ci/.build-project --build ./build --metrics ./build/metrics.txt $@;

bash
"

echo -n "Removing previous build container: "
docker rm -f ${name}

echo "
Running new build of ${project_source_dir} on ${name}
* Use CTRL-p CTRL-q to dettach
* To reattach use: docker start -a -i ${name}
"
#sleep 1

docker run --name ${name} -ti \
       -v ${project_source_dir}/.git:/builds/ValeevGroup/${project}/.git \
       ${image} bash -c "$script"
